version: "3.3"

volumes:
  web:

services:
  web :
    image: spkosana/fastapi:2.0
    container_name: web
    restart: always
    ports:
      - 8000:8000
    volumes:
      - web:/usr/src
    depends_on: 
       - database

  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - database
